PC:
  NAME: "lambda"
  IP: 192.16.1.2

NUC:
  NAME: "nuc"
  IP: 192.16.1.3
  PUB_PORT: 5566
  SUB_PORT: 5565
  GRIPPER_PUB_PORT: 5568
  GRIPPER_SUB_PORT: 5567

ROBOT:
  IP: 172.16.1.4

CONTROL:
  STATE_PUBLISHER_RATE: 100
  POLICY_RATE: 20
  TRAJ_RATE: 500
  ZMQ_NOBLOCK: true

ARM_LOGGER:
  CONSOLE:
    LOGGER_NAME: "arm_logger"
    LEVEL: "info"
    USE: true
  FILE:
    LOGGER_NAME: "logs/deoxys_control_arm_program.log"
    LEVEL: "debug"
    USE: true

GRIPPER_LOGGER:
  CONSOLE:
    LOGGER_NAME: "gripper_logger"
    LEVEL: "info"
    USE: true
  FILE:
    LOGGER_NAME: "logs/deoxys_control_gripper_program.log"
    LEVEL: "debug"
    USE: true
